print("what do you call a belt of witches?")
input("")
print("a waist of time!!")
input("----------------------------")
print("why did the frog take the bus to work?")
input("")
print("because its car got TOAD")
input("----------------------------")
print("what do dentists call their x-rays?")
input("")
print("tooth pics!!!")