print ("Self telling story")
name = input ("hello, what is your name?")
print (f"hello {name} welcome to project 1!")
print ("Your job today is to help us make decisions in our story.")
print ("") 
print ("")
location = input ("help us decided where this will take place!")
print ("~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_")
print ("")
print ("")
print (f"On a random tuesday,{name} arrived in {location}")
print (f"{name} had come to {location} for a peaceful vacation.")
print ("")
print ("")
print ("~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_")
input ("")
print ("")
print ("")
activity = input (f"Now pick a activity for {name} to do")
who = input (f"now while {activity} who does {name} meet?")
print ("")
print ("")
print ("~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_")
input ("")
print ("")
print ("")
print (f"Suddenly, {name} had the urge to {activity}")
print (f"but while {activity} {name} ran into {who}. they were so excited to see each other!")
print (f"{who} then invited {name} to go get dinner!")
print (f"'Great idea! where should we go for dinner? said {name}")
print ("")
print ("")
print ("~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_")
input ("")
print ("")
diner = input ("pick a place for them to eat!")
print ("")
print ("~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_")
input ("")
print ("")
print (f"At 6 pm {name} and {who} met up at {diner} for dinner, they spent a long long time catching up!")
print (f"At the end of the night {who} and {name} when for a night swim and returned home from their vacation")
print ("")
print ("------------------------------------------------------")
input ("")
print ("")
print ("")
print ("THE END.")
