print ("Self telling story")
name = input ("hello, what is your name?")
print (f"hello {name} welcome to project 1!")
print ("Your job today is to help us make decisions in our story.")
print ("") 
print ("")
location = input ("help us decided where this will take place!")
print ("~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~")
print (f"On a random tuesday,{name} arrived at {location}")
print (f"{name} had come to {location} for a peaceful vacation.")
print ("~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_~~-~~_")
activity = input (f"pick a activity for our {name}to do")
print (f"Suddenly, {name} had the urge to {activity}")